"""Fix default picture path

Revision ID: 61cb117ee48c
Revises: 14d421ac4884
Create Date: 2025-11-27 13:13:16.089512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '61cb117ee48c'
down_revision: Union[str, Sequence[str], None] = '14d421ac4884'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'picture_storage',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'picture_storage',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
