"""update category relation

Revision ID: 09f97f55bd40
Revises: be1fdb1ce362
Create Date: 2026-01-06 11:09:55.862908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '09f97f55bd40'
down_revision: Union[str, Sequence[str], None] = 'be1fdb1ce362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'group_uid',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('categories', 'group_uid',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
