"""fix type

Revision ID: 1e7dd49652bb
Revises: bc327831fe92
Create Date: 2025-12-11 20:31:37.968800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1e7dd49652bb'
down_revision: Union[str, Sequence[str], None] = 'bc327831fe92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('group_uid', sa.Uuid(), nullable=False),
    sa.Column('user_uid', sa.Uuid(), nullable=False),
    sa.Column('storage_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['group_uid'], ['groups.uid'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('storage_path')
    )
    op.drop_table('document')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('uid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('group_uid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_uid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('storsage_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_uid'], ['groups.uid'], name=op.f('document_group_uid_fkey')),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], name=op.f('document_user_uid_fkey')),
    sa.PrimaryKeyConstraint('uid', name=op.f('document_pkey')),
    sa.UniqueConstraint('storsage_path', name=op.f('document_storsage_path_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('documents')
    # ### end Alembic commands ###
