"""Change from uid to id on document table

Revision ID: 2a98f23dc5de
Revises: 7df3b3a68032
Create Date: 2025-12-18 16:30:58.860030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2a98f23dc5de'
down_revision: Union[str, Sequence[str], None] = '7df3b3a68032'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('documents', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('documents', 'uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('uid', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('documents', 'title')
    op.drop_column('documents', 'id')
    # ### end Alembic commands ###
