"""Remove storage path from group relation

Revision ID: 309ce39ef43a
Revises: 2a98f23dc5de
Create Date: 2025-12-18 17:06:01.750406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '309ce39ef43a'
down_revision: Union[str, Sequence[str], None] = '2a98f23dc5de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'picture_storage')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('picture_storage', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
