"""name fix

Revision ID: 3f00544f763d
Revises: f248f988962e
Create Date: 2025-12-06 21:56:21.975204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3f00544f763d'
down_revision: Union[str, Sequence[str], None] = 'f248f988962e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_jwt_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('users', 'refresh_jti_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_jti_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'refresh_jwt_hash')
    # ### end Alembic commands ###
