"""Add created at to document table

Revision ID: 5f26efb1fc01
Revises: 309ce39ef43a
Create Date: 2025-12-24 21:41:50.726243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5f26efb1fc01'
down_revision: Union[str, Sequence[str], None] = '309ce39ef43a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key(None, 'documents', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'created_at')
    op.drop_column('documents', 'category_id')
    # ### end Alembic commands ###
