"""change doc.storage_path to filename

Revision ID: 6c5066cbeaa1
Revises: b666a962916a
Create Date: 2026-01-07 23:07:24.346775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6c5066cbeaa1'
down_revision: Union[str, Sequence[str], None] = 'b666a962916a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'storage_path',
               new_column_name="file_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'file_name',
               new_column_name="storage_path")
    # ### end Alembic commands ###
