"""Add categories table

Revision ID: 7df3b3a68032
Revises: 1e7dd49652bb
Create Date: 2025-12-15 11:41:29.500798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7df3b3a68032'
down_revision: Union[str, Sequence[str], None] = '1e7dd49652bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('group_uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['group_uid'], ['groups.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('documents_storage_path_key'), 'documents', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('documents_storage_path_key'), 'documents', ['storage_path'], postgresql_nulls_not_distinct=False)
    op.drop_table('categories')
    # ### end Alembic commands ###
