"""add doc count to user

Revision ID: be1fdb1ce362
Revises: 5f26efb1fc01
Create Date: 2026-01-04 19:28:34.468960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'be1fdb1ce362'
down_revision: Union[str, Sequence[str], None] = '5f26efb1fc01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('doc_count', sa.Integer(), nullable=True))

    op.execute("UPDATE users SET doc_count = 0")

    op.alter_column(
        "users",
        "doc_count",
        nullable=False
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'doc_count')
    # ### end Alembic commands ###
