"""Init db

Revision ID: d4c97a14ec16
Revises: 
Create Date: 2025-11-06 17:10:55.055232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from src.db.models import Vector


# revision identifiers, used by Alembic.
revision: str = 'd4c97a14ec16'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='user_role'), server_default='USER', nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('documents',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('path_to_document', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('embeddings',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('document_uid', sa.Uuid(), nullable=False),
    sa.Column('embedding_vector', Vector(), nullable=True),
    sa.Column('chunk_str', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['document_uid'], ['documents.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('embeddings')
    op.drop_table('documents')
    op.drop_table('users')
    # ### end Alembic commands ###
